### ISSUE TITLE
Continue education on treehouse for Python to even out development from PHP

### ISSUE THREAD

**Issue by joverkamp** [joverkamp/SPDXHub#18]

**Comment by nchickinelli** [comment]
Nice thinking on opening up an issue for that :)—

**Comment by hangal2001** [comment]
empty issue?

**Comment by joverkamp** [comment]
Something I'm going to be doing over the weekend.

**Comment by nchickinelli** [comment]
The title for this issue is sufficient for its description. Jacob set this one up for himself, so he knows what needs to be done. It's more of a reminder for all of us about the ongoing education work than needs to be done. We'll focus our specific areas of study as we go along. 

Note that this issue is assigned specifically to Jacob. 

Right now we should keep these issues open until we hone that focus, and understand more about how we're going to distribute development.

**Comment by joverkamp** [comment]
Thanks Nick.

**Comment by joverkamp** [comment]
Moving away from python to focus on PHP.
